export const FLOORS_COUNT = 10
export const ELEVATOR_HEIGHT = 40
export const ELEVATOR_WIDTH = 40
// export const USER_GENERATE_SECONDS = 10 //?
// export const FLOOR_TRAVEL_SECONDS = 10 //?
// export const ELEVATOR_WAIT_SECONDS = 10 //?
export const USER_GENERATE_SECONDS = 3 //!
export const FLOOR_TRAVEL_SECONDS = 3 //!
export const ELEVATOR_WAIT_SECONDS = 3 //!
